apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kucero # Must match "--ds-name"
  namespace: kube-system # Must match "--ds-namespace"
spec:
  selector:
    matchLabels:
      name: kucero
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kucero
    spec:
      serviceAccountName: kucero
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: usr-bin-kubeadm
          hostPath:
            path: /usr/bin/kubeadm
            type: File
        - name: run-dbus
          hostPath:
            path: /run/dbus
      containers:
        - name: kucero
          image: jenting/kucero:v1.7.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KUCERO_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /usr/bin/kucero
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: etc-kubernetes
            - mountPath: /var/lib/kubelet
              name: var-lib-kubelet
            - mountPath: /usr/bin/kubeadm
              name: usr-bin-kubeadm
              readOnly: true
            - mountPath: /run/dbus
              name: run-dbus
